title = "ServiMariae"
baseURL = 'https://marcello1099.github.io/servi-mariae/'

languageCode = 'en-us'
defaultContentLanguage = "en-gb"

theme = "servi-mariae"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/en"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    pageRef = "/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef = "posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-gb.params]
  description = "A Catholic journal."
  mainSections = ['posts']

  [Languages.en-gb.params.author]
    avatar = "avatar.png"
    name = "ServiMariae"
    description = "Catholic reflections — Ad Iesum per Mariam"

  [Languages.en-gb.params.authors]
    [Languages.en-gb.params.authors.marcello]
      name = "Marcello Mariani"
      avatar = "authors/marcello.jpg"
      url = "https://www.linkedin.com/in/marcello-mariani-m/"

############################## Spanish language ################################
[Languages.es-es]
  languageName = "Español"
  languageCode = "es-es"
  contentDir = "content/es"
  weight = 2

  [Languages.es-es.menu]
  [[Languages.es-es.menu.main]]
    pageRef = "/"
    name = 'Inicio'
    url = '/es-es/'
    weight = 10
  [[Languages.es-es.menu.main]]
    pageRef = "posts"
    name = 'Publicaciones'
    url = '/es-es/posts/'
    weight = 20

  [Languages.es-es.params]
    description = "Una revista católica."
    mainSections = ['posts']

    [Languages.es-es.params.authors]
      [Languages.es-es.params.authors.marcello]
        name = "Marcello Mariani"
        avatar = "authors/marcello.jpg"
        url = "https://www.linkedin.com/in/marcello-mariani-m/"
