name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_Linux-64bit.tar.gz
          tar -C $(RUNNER_TEMP) -zxvf /tmp/hugo.tar.gz hugo
          sudo mv $(RUNNER_TEMP)/hugo /usr/local/bin/

      - name: Build
        run: |
          hugo --minify

      - name: Disable Jekyll
        run: touch built-site/.nojekyll

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* built-site/
          cd built-site
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Deploy site - $(date)'
          git push